TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'JohannesSteu.Neos.NodeTypes': TRUE
    userInterface:
      translation:
        autoInclude:
          'JohannesSteu.Neos.NodeTypes': ['NodeTypes/*']