
JohannesSteu:
  Neos:
    NodeTypes:
      All:
        # if one of these are set to TRUE the css and js will always be included
        loadCSS: FALSE
        loadJS: FALSE

      # if the above All.loadCSS // All.LoadJS are set to false the CSS / JS for a specific element will only
      # be loaded if there is an element of that NodeType on the current page
      Accordeon:
        loadCSS: FALSE
        loadJS: FALSE
      Slideshow:
        loadCSS: FALSE
        loadJS: FALSE

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          JohannesSteu.Neos.NodeTypes:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        JohannesSteu.Neos.NodeTypes: true
