
JohannesSteu:
  Neos:
    NodeTypes:
      All:
        loadCSS: false
        loadJS: false
      Accordeon:
        loadCSS: false
        loadJS: false
      Slideshow:
        loadCSS: false
        loadJS: false
Neos:
  Neos:
    typoScript:
      autoInclude:
        JohannesSteu.Neos.NodeTypes: true
    userInterface:
      translation:
        autoInclude:
          JohannesSteu.Neos.NodeTypes:
            - 'NodeTypes/*'
